### ISSUE TITLE
.gitignore Updates

### ISSUE THREAD

**Issue by melloware** [rmpestano/quarkus-omnifaces#6]
To fix the target folder issues..

See: https://labs.consol.de/development/git/2017/02/22/gitignore.html

target needs a trailing backslash to ignore ANY target folder even in subdirectories.

```
build/
dist/
*.jsfdia
*.asc
*.tern-project
/bin
target/
/.settings
/.project
/.classpath
rebel.xml
*.iml
/.idea
```

**Comment by rmpestano** [comment]
Thank you @melloware!
